app:
  name: "NetScan"
  version: "1.0.0"

server:
  port: 8080
  mode: "debug"

database:
  host: "localhost"
  port: 5432
  user: "netscan"
  password: "netscan"
  dbname: "netscan"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

logging:
  level: "info"
  format: "text"

security:
  agent_token_secret: "change-me-in-production"
  token_expiry: "720h"